const characters = [
  // Hiragana
  { char: "あ", type: "hiragana", pair: "a" },
  { char: "い", type: "hiragana", pair: "i" },
  { char: "う", type: "hiragana", pair: "u" },
  { char: "え", type: "hiragana", pair: "e" },
  { char: "お", type: "hiragana", pair: "o" },
  { char: "か", type: "hiragana", pair: "ka" },
  { char: "き", type: "hiragana", pair: "ki" },
  { char: "く", type: "hiragana", pair: "ku" },
  { char: "け", type: "hiragana", pair: "ke" },
  { char: "こ", type: "hiragana", pair: "ko" },
  { char: "さ", type: "hiragana", pair: "sa" },
  { char: "し", type: "hiragana", pair: "shi" },
  { char: "す", type: "hiragana", pair: "su" },
  { char: "せ", type: "hiragana", pair: "se" },
  { char: "そ", type: "hiragana", pair: "so" },
  { char: "た", type: "hiragana", pair: "ta" },
  { char: "ち", type: "hiragana", pair: "chi" },
  { char: "つ", type: "hiragana", pair: "tsu" },
  { char: "て", type: "hiragana", pair: "te" },
  { char: "と", type: "hiragana", pair: "to" },
  { char: "な", type: "hiragana", pair: "na" },
  { char: "に", type: "hiragana", pair: "ni" },
  { char: "ぬ", type: "hiragana", pair: "nu" },
  { char: "ね", type: "hiragana", pair: "ne" },
  { char: "の", type: "hiragana", pair: "no" },
  { char: "は", type: "hiragana", pair: "ha" },
  { char: "ひ", type: "hiragana", pair: "hi" },
  { char: "ふ", type: "hiragana", pair: "fu" },
  { char: "へ", type: "hiragana", pair: "he" },
  { char: "ほ", type: "hiragana", pair: "ho" },
  { char: "ま", type: "hiragana", pair: "ma" },
  { char: "み", type: "hiragana", pair: "mi" },
  { char: "む", type: "hiragana", pair: "mu" },
  { char: "め", type: "hiragana", pair: "me" },
  { char: "も", type: "hiragana", pair: "mo" },
  { char: "や", type: "hiragana", pair: "ya" },
  { char: "ゆ", type: "hiragana", pair: "yu" },
  { char: "よ", type: "hiragana", pair: "yo" },
  { char: "ら", type: "hiragana", pair: "ra" },
  { char: "り", type: "hiragana", pair: "ri" },
  { char: "る", type: "hiragana", pair: "ru" },
  { char: "れ", type: "hiragana", pair: "re" },
  { char: "ろ", type: "hiragana", pair: "ro" },
  { char: "わ", type: "hiragana", pair: "wa" },
  { char: "を", type: "hiragana", pair: "wo" },
  { char: "ん", type: "hiragana", pair: "n" },

  // Katakana
  { char: "ア", type: "katakana", pair: "a" },
  { char: "イ", type: "katakana", pair: "i" },
  { char: "ウ", type: "katakana", pair: "u" },
  { char: "エ", type: "katakana", pair: "e" },
  { char: "オ", type: "katakana", pair: "o" },
  { char: "カ", type: "katakana", pair: "ka" },
  { char: "キ", type: "katakana", pair: "ki" },
  { char: "ク", type: "katakana", pair: "ku" },
  { char: "ケ", type: "katakana", pair: "ke" },
  { char: "コ", type: "katakana", pair: "ko" },
  { char: "サ", type: "katakana", pair: "sa" },
  { char: "シ", type: "katakana", pair: "shi" },
  { char: "ス", type: "katakana", pair: "su" },
  { char: "セ", type: "katakana", pair: "se" },
  { char: "ソ", type: "katakana", pair: "so" },
  { char: "タ", type: "katakana", pair: "ta" },
  { char: "チ", type: "katakana", pair: "chi" },
  { char: "ツ", type: "katakana", pair: "tsu" },
  { char: "テ", type: "katakana", pair: "te" },
  { char: "ト", type: "katakana", pair: "to" },
  { char: "ナ", type: "katakana", pair: "na" },
  { char: "ニ", type: "katakana", pair: "ni" },
  { char: "ヌ", type: "katakana", pair: "nu" },
  { char: "ネ", type: "katakana", pair: "ne" },
  { char: "ノ", type: "katakana", pair: "no" },
  { char: "ハ", type: "katakana", pair: "ha" },
  { char: "ヒ", type: "katakana", pair: "hi" },
  { char: "フ", type: "katakana", pair: "fu" },
  { char: "ヘ", type: "katakana", pair: "he" },
  { char: "ホ", type: "katakana", pair: "ho" },
  { char: "マ", type: "katakana", pair: "ma" },
  { char: "ミ", type: "katakana", pair: "mi" },
  { char: "ム", type: "katakana", pair: "mu" },
  { char: "メ", type: "katakana", pair: "me" },
  { char: "モ", type: "katakana", pair: "mo" },
  { char: "ヤ", type: "katakana", pair: "ya" },
  { char: "ユ", type: "katakana", pair: "yu" },
  { char: "ヨ", type: "katakana", pair: "yo" },
  { char: "ラ", type: "katakana", pair: "ra" },
  { char: "リ", type: "katakana", pair: "ri" },
  { char: "ル", type: "katakana", pair: "ru" },
  { char: "レ", type: "katakana", pair: "re" },
  { char: "ロ", type: "katakana", pair: "ro" },
  { char: "ワ", type: "katakana", pair: "wa" },
  { char: "ヲ", type: "katakana", pair: "wo" },
  { char: "ン", type: "katakana", pair: "n" },

  // Kanji
  { char: "日", type: "kanji", pair: "sun / day" },
  { char: "月", type: "kanji", pair: "moon / month" },
  { char: "火", type: "kanji", pair: "fire" },
  { char: "水", type: "kanji", pair: "water" },
  { char: "木", type: "kanji", pair: "tree / wood" },
  { char: "金", type: "kanji", pair: "gold / money" },
  { char: "土", type: "kanji", pair: "earth / soil" },
  { char: "山", type: "kanji", pair: "mountain" },
  { char: "川", type: "kanji", pair: "river" },
  { char: "田", type: "kanji", pair: "rice field" },
  { char: "人", type: "kanji", pair: "person" },
  { char: "口", type: "kanji", pair: "mouth" },
  { char: "目", type: "kanji", pair: "eye" },
  { char: "耳", type: "kanji", pair: "ear" },
  { char: "手", type: "kanji", pair: "hand" },
  { char: "足", type: "kanji", pair: "foot / leg" },
  { char: "大", type: "kanji", pair: "big" },
  { char: "小", type: "kanji", pair: "small" },
  { char: "中", type: "kanji", pair: "middle / inside" },
  { char: "上", type: "kanji", pair: "up / above" },
  { char: "下", type: "kanji", pair: "down / below" },
  { char: "左", type: "kanji", pair: "left" },
  { char: "右", type: "kanji", pair: "right" },
  { char: "一", type: "kanji", pair: "one" },
  { char: "二", type: "kanji", pair: "two" },
  { char: "三", type: "kanji", pair: "three" },
  { char: "四", type: "kanji", pair: "four" },
  { char: "五", type: "kanji", pair: "five" },
  { char: "六", type: "kanji", pair: "six" },
  { char: "七", type: "kanji", pair: "seven" },
  { char: "八", type: "kanji", pair: "eight" },
  { char: "九", type: "kanji", pair: "nine" },
  { char: "十", type: "kanji", pair: "ten" },
  { char: "百", type: "kanji", pair: "hundred" },
  { char: "千", type: "kanji", pair: "thousand" },
];